#!/bin/bash
qstat -of /tmp/q4 -raw ","  -default q4s 200.75.30.183 |head -1
IP=`cat /tmp/q4|head -1|awk -F"," '{print $2}'`
NAME=`cat /tmp/q4|head -1|awk -F"," '{print $3}'`
MAPA=`cat /tmp/q4|head -1|awk -F"," '{print $4}'`
MAXP=`cat /tmp/q4|head -1|awk -F"," '{print $5}'`
CURRENT=`cat /tmp/q4|head -1|awk -F"," '{print $6}'`
echo IP: $IP\   Nombre: $NAME\  Mapa: $MAPA\  Maximo_Player: $CURRENT/$MAXP
chmod 777 /tmp/q4
